# Generated by Django 4.1.1 on 2022-09-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=30)),
                ('study_url', models.CharField(max_length=300)),
                ('study_title', models.CharField(max_length=500)),
                ('study_status', models.CharField(max_length=50)),
                ('sponsor_collaborators', models.CharField(max_length=500)),
            ],
        ),
    ]
